[build]
builder = "dockerfile"
dockerfilePath = "apps/desktop/Dockerfile"
watchPatterns = ["apps/desktop/**"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
